<a href="https://colab.research.google.com/github/afrahriyaz/TensorFlow/blob/main/tensorflow1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Introduction to Tensors

In [3]:
# Import tenserlow
import tensorflow as tf
print(tf.__version__)

2.7.0


In [4]:
#creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#check number of dimensions of tensor(ndim)
scalar.ndim

0

In [6]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
#check the dimension of our vector
vector.ndim

1

In [8]:
#create a matrix
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
#create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
#no of dimentions of another matrix
another_matrix.ndim

2

In [12]:
#creating a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [11,12,13]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]], dtype=int32)>

In [13]:
tensor.ndim

3

###creating a variable tensor

In [14]:
variable_tensor = tf.Variable([[2,3],
                              [5,7]])
variable_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [5, 7]], dtype=int32)>

In [15]:
variable_tensor[0].assign([10,20])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[10, 20],
       [ 5,  7]], dtype=int32)>

###creating a random tensor 

In [16]:
random_tensor = tf.random.Generator.from_seed(42)

In [17]:
random_tensor.normal(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [18]:
random_tensor2 = tf.random.Generator.from_seed(42)
random_tensor2.normal(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [19]:
random_tensor, random_tensor2,  random_tensor == random_tensor2

(<tensorflow.python.ops.stateful_random_ops.Generator at 0x7fdd4831c190>,
 False)

In [20]:
random1 = tf.random.Generator.from_seed(7)
random1 = random1.normal(shape=(3,2))
random2 = tf.random.Generator.from_seed(7)
random2 = random2.normal(shape=(3,2))
random1, random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###shuffling the order of elements in a tensor

In [21]:
not_shuffled = tf.constant([[10,7],
                           [2,3],
                           [5,9]])
not_shuffled.ndim

2

In [22]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3],
       [ 5,  9]], dtype=int32)>

In [23]:
#gives different random order everytime it is run
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  9],
       [10,  7],
       [ 2,  3]], dtype=int32)>

In [24]:
#gives same random order no matter how many times we run it
tf.random.set_seed(2)
tf.random.shuffle(not_shuffled,seed=2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  9],
       [ 2,  3],
       [10,  7]], dtype=int32)>

###other ways to make tensors

In [25]:
tf.ones([5,2])

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [26]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [27]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [28]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [29]:
B = tf.constant(numpy_A, shape=(2,3,4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

###getting information from tensors

In [30]:
rank4tensor = tf.zeros(shape=[2,3,4,5])
rank4tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
rank4tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [32]:
rank4tensor.shape, rank4tensor.ndim, tf.size(rank4tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [33]:
#get various attributes of our tensor
print("datatype of every element: ",rank4tensor.dtype)
print("nnumber of dimentions(rank): ", rank4tensor.ndim)
print("shape of tensor: ",rank4tensor.shape)
print("elements along the 0 axis: ",rank4tensor.shape[0])
print("elements along the last axis: ", rank4tensor.shape[-1])
print("total number of elements in our tensor: ",tf.size(rank4tensor))

datatype of every element:  <dtype: 'float32'>
nnumber of dimentions(rank):  4
shape of tensor:  (2, 3, 4, 5)
elements along the 0 axis:  2
elements along the last axis:  5
total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)


###Indexing tensors

In [35]:
#like in python
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [36]:
#similarly
#getting first two elements of each dimention
rank4tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [39]:
#getting the first element from each index except the final one
rank4tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [40]:
rank2tensor = tf.constant([[2,5],
                           [3,7]])
rank2tensor.shape, rank2tensor.ndim

(TensorShape([2, 2]), 2)

In [43]:
#get the last item of each of rank2tensor
rank2tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 7], dtype=int32)>

In [44]:
#add in extra dimension to our rank 2 tensor
rank3tensor = rank2tensor[..., tf.newaxis]
rank3tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [5]],

       [[3],
        [7]]], dtype=int32)>

In [45]:
#alternative to tf.newaxis
tf.expand_dims(rank2tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [5]],

       [[3],
        [7]]], dtype=int32)>

In [46]:
#expand 0 axis
tf.expand_dims(rank2tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 5],
        [3, 7]]], dtype=int32)>

###Manipulating tensors(tensor operation)
**Basic operations**

`+`,`-`,`*`,`/`

In [47]:
#adding 
tensor = tf.constant([[1,2],
                      [3,5]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 15]], dtype=int32)>

In [48]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 5]], dtype=int32)>

In [49]:
#multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 50]], dtype=int32)>

In [50]:
#subtraction
tensor -3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-2, -1],
       [ 0,  2]], dtype=int32)>

In [52]:
#we can use use tensorflow built in func too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 50]], dtype=int32)>

In [53]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 5]], dtype=int32)>

**Matrix multiplication**

We can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [55]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[1 2]
 [3 5]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 12],
       [18, 31]], dtype=int32)>

In [56]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 25]], dtype=int32)>

In [57]:
#matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 12],
       [18, 31]], dtype=int32)>

In [64]:
#create a 3,2 tensor
X = tf.constant([[1,2],
                [3,4],
                [5,6]])
#create a 2,3 tensor
Y = tf.constant([[1,2],
                 [6,3],
                [9,7]])
#multiply them
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 7, 20, 20],
       [15, 42, 46],
       [23, 64, 72]], dtype=int32)>

In [65]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 7, 20, 20],
       [15, 42, 46],
       [23, 64, 72]], dtype=int32)>

In [66]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 5]], dtype=int32)>

In [67]:
#reshaping x instead of y
tf.reshape(X, shape=(2,3)) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 29],
       [88, 65]], dtype=int32)>

In [68]:
tf.matmul(tf.reshape(X, shape=(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 29],
       [88, 65]], dtype=int32)>

In [70]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [73]:
tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [74]:
#try matrix multiplication with transpose rather than reshaping
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[64, 46],
       [80, 58]], dtype=int32)>

In [75]:
#perform dot product(matrix multiplication) using tf.tensordot
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [6, 3],
        [9, 7]], dtype=int32)>)

In [76]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[64, 46],
       [80, 58]], dtype=int32)>

In [77]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 12, 23],
       [11, 30, 55],
       [17, 48, 87]], dtype=int32)>

In [78]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 7, 20, 20],
       [15, 42, 46],
       [23, 64, 72]], dtype=int32)>

### Changing the datatype of a tensor

In [79]:
# create a new tensor with default datatype(float)
C = tf.constant([1.4,1.7])
C.dtype

tf.float32

In [80]:
D = tf.constant([3,4])
D.dtype

tf.int32

In [82]:
#change float32 to float16
E = tf.cast(C, dtype=tf.float16)
C, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.4, 1.7], dtype=float32)>,
 tf.float16)

In [84]:
#change from int32 to float32
F = tf.cast(D, dtype=tf.float32)
F, F.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>,
 tf.float32)

###Aggregating tensors

In [85]:
#Getting the absolute values
A = tf.constant([-7,-10])
A

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [86]:
tf.abs(A)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [87]:
#create a random tensor
tens = tf.constant(np.random.randint(0,100,size=50))
tens

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([25, 68, 40, 26,  5, 65, 92, 81, 77, 63, 91, 47, 68, 24, 72, 44, 27,
       67, 34,  3, 14, 54, 93, 13, 66, 54, 51, 99, 60, 48, 99, 44,  6, 50,
       16, 79, 40, 85, 37, 90, 56, 32, 36, 73, 18,  9, 51,  0, 64, 99])>

In [88]:
tf.size(tens), tens.shape, tens.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [89]:
tf.reduce_min(tens) #min element in tensor

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [90]:
tf.reduce_max(tens) #max element in tensor

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [91]:
tf.reduce_mean(tens) #mean of the tensor

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [92]:
tf.reduce_sum(tens) #sum of the elements of tensor

<tf.Tensor: shape=(), dtype=int64, numpy=2555>

In [93]:
#find variance of tensor
import tensorflow_probability as tfp
tfp.stats.variance(tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [97]:
tf.math.reduce_std(tf.cast(tens, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.139118>