<a href="https://colab.research.google.com/github/afrahriyaz/TensorFlow/blob/main/tensorflow1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Introduction to Tensors

In [1]:
# Import tenserlow
import tensorflow as tf
print(tf.__version__)

2.7.0


In [2]:
#creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check number of dimensions of tensor(ndim)
scalar.ndim

0

In [4]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#check the dimension of our vector
vector.ndim

1

In [6]:
#create a matrix
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
#create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
#no of dimentions of another matrix
another_matrix.ndim

2

In [10]:
#creating a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [11,12,13]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]], dtype=int32)>

In [11]:
tensor.ndim

3

###creating a variable tensor

In [12]:
variable_tensor = tf.Variable([[2,3],
                              [5,7]])
variable_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [5, 7]], dtype=int32)>

In [13]:
variable_tensor[0].assign([10,20])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[10, 20],
       [ 5,  7]], dtype=int32)>

###creating a random tensor 

In [14]:
random_tensor = tf.random.Generator.from_seed(42)

In [15]:
random_tensor.normal(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [16]:
random_tensor2 = tf.random.Generator.from_seed(42)
random_tensor2.normal(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [17]:
random_tensor, random_tensor2,  random_tensor == random_tensor2

(<tensorflow.python.ops.stateful_random_ops.Generator at 0x7f9d210cc990>,
 False)

In [18]:
random1 = tf.random.Generator.from_seed(7)
random1 = random1.normal(shape=(3,2))
random2 = tf.random.Generator.from_seed(7)
random2 = random2.normal(shape=(3,2))
random1, random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###shuffling the order of elements in a tensor

In [19]:
not_shuffled = tf.constant([[10,7],
                           [2,3],
                           [5,9]])
not_shuffled.ndim

2

In [20]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3],
       [ 5,  9]], dtype=int32)>

In [21]:
#gives different random order everytime it is run
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  3],
       [ 5,  9],
       [10,  7]], dtype=int32)>

In [22]:
#gives same random order no matter how many times we run it
tf.random.set_seed(2)
tf.random.shuffle(not_shuffled,seed=2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  9],
       [ 2,  3],
       [10,  7]], dtype=int32)>

###other ways to make tensors

In [23]:
tf.ones([5,2])

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [24]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [25]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [26]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [27]:
B = tf.constant(numpy_A, shape=(2,3,4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

###getting information from tensors

In [28]:
rank4tensor = tf.zeros(shape=[2,3,4,5])
rank4tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
rank4tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [30]:
rank4tensor.shape, rank4tensor.ndim, tf.size(rank4tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [31]:
#get various attributes of our tensor
print("datatype of every element: ",rank4tensor.dtype)
print("nnumber of dimentions(rank): ", rank4tensor.ndim)
print("shape of tensor: ",rank4tensor.shape)
print("elements along the 0 axis: ",rank4tensor.shape[0])
print("elements along the last axis: ", rank4tensor.shape[-1])
print("total number of elements in our tensor: ",tf.size(rank4tensor))

datatype of every element:  <dtype: 'float32'>
nnumber of dimentions(rank):  4
shape of tensor:  (2, 3, 4, 5)
elements along the 0 axis:  2
elements along the last axis:  5
total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)


###Indexing tensors

In [32]:
#like in python
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [33]:
#similarly
#getting first two elements of each dimention
rank4tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [34]:
#getting the first element from each index except the final one
rank4tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [35]:
rank2tensor = tf.constant([[2,5],
                           [3,7]])
rank2tensor.shape, rank2tensor.ndim

(TensorShape([2, 2]), 2)

In [36]:
#get the last item of each of rank2tensor
rank2tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 7], dtype=int32)>

In [37]:
#add in extra dimension to our rank 2 tensor
rank3tensor = rank2tensor[..., tf.newaxis]
rank3tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [5]],

       [[3],
        [7]]], dtype=int32)>

In [38]:
#alternative to tf.newaxis
tf.expand_dims(rank2tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [5]],

       [[3],
        [7]]], dtype=int32)>

In [39]:
#expand 0 axis
tf.expand_dims(rank2tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 5],
        [3, 7]]], dtype=int32)>

###Manipulating tensors(tensor operation)
**Basic operations**

`+`,`-`,`*`,`/`

In [40]:
#adding 
tensor = tf.constant([[1,2],
                      [3,5]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 15]], dtype=int32)>

In [41]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 5]], dtype=int32)>

In [42]:
#multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 50]], dtype=int32)>

In [43]:
#subtraction
tensor -3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-2, -1],
       [ 0,  2]], dtype=int32)>

In [44]:
#we can use use tensorflow built in func too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 50]], dtype=int32)>

In [45]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 5]], dtype=int32)>

**Matrix multiplication**

We can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [46]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[1 2]
 [3 5]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 12],
       [18, 31]], dtype=int32)>

In [47]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 25]], dtype=int32)>

In [48]:
#matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 12],
       [18, 31]], dtype=int32)>

In [49]:
#create a 3,2 tensor
X = tf.constant([[1,2],
                [3,4],
                [5,6]])
#create a 2,3 tensor
Y = tf.constant([[1,2],
                 [6,3],
                [9,7]])
#multiply them
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 7, 20, 20],
       [15, 42, 46],
       [23, 64, 72]], dtype=int32)>

In [50]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 7, 20, 20],
       [15, 42, 46],
       [23, 64, 72]], dtype=int32)>

In [51]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 5]], dtype=int32)>

In [52]:
#reshaping x instead of y
tf.reshape(X, shape=(2,3)) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 29],
       [88, 65]], dtype=int32)>

In [53]:
tf.matmul(tf.reshape(X, shape=(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 29],
       [88, 65]], dtype=int32)>

In [54]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [55]:
tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [56]:
#try matrix multiplication with transpose rather than reshaping
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[64, 46],
       [80, 58]], dtype=int32)>

In [57]:
#perform dot product(matrix multiplication) using tf.tensordot
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [6, 3],
        [9, 7]], dtype=int32)>)

In [58]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[64, 46],
       [80, 58]], dtype=int32)>

In [59]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 12, 23],
       [11, 30, 55],
       [17, 48, 87]], dtype=int32)>

In [60]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 7, 20, 20],
       [15, 42, 46],
       [23, 64, 72]], dtype=int32)>

### Changing the datatype of a tensor

In [61]:
# create a new tensor with default datatype(float)
C = tf.constant([1.4,1.7])
C.dtype

tf.float32

In [62]:
D = tf.constant([3,4])
D.dtype

tf.int32

In [63]:
#change float32 to float16
E = tf.cast(C, dtype=tf.float16)
C, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.4, 1.7], dtype=float32)>,
 tf.float16)

In [64]:
#change from int32 to float32
F = tf.cast(D, dtype=tf.float32)
F, F.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>,
 tf.float32)

###Aggregating tensors

In [65]:
#Getting the absolute values
A = tf.constant([-7,-10])
A

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [66]:
tf.abs(A)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [67]:
#create a random tensor
tens = tf.constant(np.random.randint(0,100,size=50))
tens

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([88,  8, 91, 41, 11, 31, 48,  8, 85, 94,  1, 33, 27, 91, 74, 77, 66,
       80, 67, 82, 13, 59, 33, 80, 79, 24, 60, 24, 43, 43, 28, 52, 42, 36,
       49, 20, 40, 88, 57, 55, 52, 75, 25, 89, 86, 15, 27, 55,  2, 17])>

In [68]:
tf.size(tens), tens.shape, tens.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [69]:
tf.reduce_min(tens) #min element in tensor

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [70]:
tf.reduce_max(tens) #max element in tensor

<tf.Tensor: shape=(), dtype=int64, numpy=94>

In [71]:
tf.reduce_mean(tens) #mean of the tensor

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [72]:
tf.reduce_sum(tens) #sum of the elements of tensor

<tf.Tensor: shape=(), dtype=int64, numpy=2471>

In [77]:
#find variance of tensor
import tensorflow_probability as tfp
tfp.stats.variance(tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [74]:
tf.math.reduce_std(tf.cast(tens, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.56018>

In [75]:
tf.math.reduce_variance(tf.cast(tens, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=759.5636>

###finding positional max and min

In [82]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [83]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [84]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [85]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [86]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [89]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

###squeezing the tensor

In [91]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [92]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape

TensorShape([50])

###One hot encoding

In [93]:
#create a list of indices
some_list = [0, 1, 2, 3]
#one hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [94]:
tf.one_hot(some_list, depth=4, on_value="me", off_value="you")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'me', b'you', b'you', b'you'],
       [b'you', b'me', b'you', b'you'],
       [b'you', b'you', b'me', b'you'],
       [b'you', b'you', b'you', b'me']], dtype=object)>

### finding access to GPUs

In [3]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
!nvidia-smi

Thu Nov 25 13:53:19 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P8    30W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------